apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-deployment
  labels:
    app: debug-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: debug-apps
  template:
    metadata:
      labels:
        app: debug-app
    spec:
      containers:
        - name: debug-app
          image: nginx:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          resources:
            requests:
              cpu: 50m
              memory: 63Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
